services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./configs/syncthing:/config
      - ./images:/config/images
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  kube-photos:
    image: ghcr.io/masochieves/kube-photos:latest
    container_name: kube-photos
    restart: unless-stopped
    volumes:
      - ./images:/app/images
    privileged: true
    environment:
      - "UDEV=1"

  caddy:
    image: caddy:2.9-alpine
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./configs/caddy:/etc/caddy
      - ./configs/caddy_data:/data
