name: Docker Image CI

on:
  push:
    branches:
      - main
      - dockerize
  pull_request:
    branches:
      - main
      - dockerize
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag server:$(date +%s)
